### ISSUE TITLE
Loading Model Issues

### ISSUE THREAD

**Issue by DRRXYY** [usccolumbia/CSPBenchMetrics#1]
Hello, I'm sorry to bother you. I encountered this error while running your code. I hope you can give me some advice. Thank you!
this: (ValueError: File format not supported: filepath=/root/anaconda3/envs/metrics/lib/python3.9/site-packages/m3gnet/models/MP-2021.2.8-EFS/m3gnet. Keras 3 only supports V3 `.keras` and `.weights.h5` files, or legacy V1/V2 `.h5` files.)

**Comment by hallofuture** [comment]
Hi, thanks for trying our approach. I guess it should be the the version incompatible for the tensorflow.
You can try tensorflow= 2.9.3
